name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
      - development

jobs:
  pr_workflow:
    name: PR Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install

      - name: Build app
        run: yarn build
